name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: garciafamilymedicineacr.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t garciafamilymedicine-directus-backend:${{ github.sha }} .
        docker tag garciafamilymedicine-directus-backend:${{ github.sha }} garciafamilymedicineacr.azurecr.io/garciafamilymedicine-directus-backend:${{ github.sha }}
        docker push garciafamilymedicineacr.azurecr.io/garciafamilymedicine-directus-backend:${{ github.sha }}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: garciafamilymedicine-backend
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: garciafamilymedicineacr.azurecr.io/garciafamilymedicine-directus-backend:${{ github.sha }}
